version: 2.1

workflows:
  test-deploy:
    jobs:
      - build-and-test

jobs:
  build-and-test:
    docker:
      - image: cimg/node:20.19 # Stable Node version for Vite
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: npm install



      - run:
          name: Build project
          command: npm run build
